name: Master commit

on:
  push:
    branches:
      - master

jobs:
  check-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Getting the repo
        uses: actions/checkout@v2
      - name: Install yarn dependencies
        run: |
          yarn install --ci
      - name: Check TypeScript
        run: |
          yarn tscheck
      - name: Test
        run: |
          yarn test --ci --coverage

  build-and-deploy:
    needs: check-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Getting the repo
        uses: actions/checkout@v2
      - name: Install React Native CLI
        run: |
          yarn global add react-native-cli
      - name: Install yarn dependencies
        run: |
          yarn install --ci
      - name: Build Android Release
        run: |
          cd android && ./gradlew bundleRelease
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-release.aab
          path: android/app/build/outputs/bundle/release/
      - name: Upload app-release.aab to Google Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ SERVICE_ACCOUNT_JSON }}
          packageName: ovh.dtrw.apps.scorer
          releaseFile: android/app/build/outputs/bundle/release/app-release.aab
          track: production
    
