name: Continuous Integration

on:
    pull_request:
        branches:
            - master
            - dev

jobs:
    check-and-test:
        runs-on: ubuntu-latest
        steps:
            - name: Getting the repo
              uses: actions/checkout@v2
            - name: Install yarn dependencies
              run: |
                  yarn install --ci
            - name: Check TypeScript
              run: |
                  yarn tscheck
            - name: Test
              run: |
                  yarn test

    build:
        runs-on: ubuntu-latest
        steps:
            - name: Getting the repo
              uses: actions/checkout@v2
            - name: Install React Native CLI
              run: |
                  yarn global add react-native-cli
            - name: Install yarn dependencies
              run: |
                  yarn install --ci
            - name: Build Android Release
              run: |
                  cd android && ./gradlew bundleRelease
            - name: Upload Artifact
              uses: actions/upload-artifact@v2
              with:
                  name: app-release.apk
                  path: android/app/build/outputs/apk/release/
